GET http://localhost:5005/

POST http://localhost:5005/auth/register
Content-Type: application/json

{
    "nama" : "Rosa",
    "email" : "rosa@mail.com",
    "password" : "password",
    "username" : "rosaam",
    "telepon" : "0"
}

POST http://localhost:5005/auth/login
Content-Type: application/json

{
    "email": "rosa@mail.com",
    "password": "password"
}